#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"%Z%%M%	%I%	%E% SMI"

. /lib/svc/share/smf_include.sh

# The real daemon is not started in a non-global zone. But we need to
# create a dummy background process to preserve contract lifetime.

if smf_is_nonglobalzone; then
	(while true ; do sleep 3600 ; done) & 
	exit $SMF_EXIT_OK
fi

# Start the dlmgmtd daemon.
/sbin/dlmgmtd
DLMGMTD_STATUS=$?

# Wait for datalink management to properly start
TIMEOUT=20
CONF=/etc/physical-mac-addresses.conf
TMPCONF=/tmp/physical-mac-addresses.conf
while true; do
	# Read physical mac address information and ignore VirtualBox mac addresses (that use the unregistered MAC OUI 08:00:27)
	ADDRESSES=$(/usr/sbin/dladm show-phys -p -m -o ADDRESS 2>/dev/null | grep -v '^8:0:27:' | /usr/gnu/bin/sort | tee $TMPCONF)
	if [ ! -z "$ADDRESSES" ]; then
		echo "Found addresses: $ADDRESSES"
		# Do not use the file if aggregates are present (i.e. we have duplicates in the generated mac addresses file)
		if /usr/gnu/bin/uniq $TMPCONF | /usr/gnu/bin/diff $TMPCONF - >/dev/null 2>&1; then
			echo "Moving $TMPCONF to $CONF"
			mv $TMPCONF $CONF
		else
			echo "Something went wrong when creating $TMPCONF"
		fi
		break
	fi

	echo "Can't get mac addresses right now. We found no mac addresses."
    echo "Timeout in $TIMEOUT seconds"

	if [ "$TIMEOUT" == "0" ]; then
		break
	else
		((TIMEOUT--))
	fi
	sleep 1
done

if [ $DLMGMTD_STATUS = 0 ]; then
	exit $SMF_EXIT_OK
else
	exit $SMF_EXIT_ERR_FATAL
fi
